server:
  port: 22100
spring:
  application:
    name: xc-service-base-filesystem
  data: #mongo配置
    mongodb:
      database: xc_fs
      uri: mongodb://127.0.0.1:27017
  servlet: #SpringMVC上传文件配置
    multipart:
      enabled: true #默认支持文件上传.
      file-size-threshold: 0 #支持文件写入磁盘.
      location: # 上传文件的临时目录
      max-file-size: 1MB # 最大支持文件大小
      max-request-size: 30MB # 最大支持请求大小
xuecheng:
  fastdfs:
    connect_timeout_in_seconds: 30000
    network_timeout_in_seconds: 30000
    charset: UTF-8
    tracker_servers: 39.107.65.111:22122
