server:
  port: 31001
spring:
  application:
    name: xc-service-manager-cms
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtualHost: /
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: xc_cms